<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
    protected $with=['category','author']; //This gets rid of n plus one trap problem
   // protected $fillable = ['title', 'excerpt', 'body'];
   /* public function getRouteKeyName()
    {
        return parent::getRouteKeyName('slug'); // TODO: Change the autogenerated stub
    }*/
    public function category(){
        return $this->belongsTo(Category::class); //elequent relationship
}
    public function author(){
        return $this->belongsTo(User::class, 'user_id'); //elequent relationship
    }
}
